baseURL = "http://www.charlesetc.com"
languageCode = "en-us"
title = "Charles, etc"
theme = "hyde"
pygmentsCodeFences = true
pygmentsStyle = "autumn"
sectionPagesMenu = "main"
pluralizeListTitles = false
relativeURLs = true

[params]
