// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $('#question_one').plaxify({
      "xRange": 40,
      "yRange": 40
    });
    $('#question_two').plaxify({
      "xRange": 20,
      "yRange": 20,
      "invert": true
    });
    return $.plax.enable();
  });

}).call(this);
